apiVersion: v1
kind: Service
metadata:
  name:  docs-site-svc
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: docs-site
    group: {{ .Release.Name }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
  - name: rest
    port: 80
    targetPort: 8080
    protocol: TCP 
  # - name: grpc
  #   port: 50051
  #   protocol: TCP 
  selector:
    app: docs-site
    group: {{ .Release.Name }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}