apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: website
    group: {{ .Release.Name }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: website
      group: {{ .Release.Name }}
  template:
    metadata:
      labels: {{- include "common.labels.matchLabels" . | nindent 8 }}
        app: website
        group: {{ .Release.Name }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.web.podSecurityContext | nindent 8 }}
      containers:
        - name: website
          securityContext:
            {{- toYaml .Values.web.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.web.image.repository }}:{{ if .Values.web.image.imageTag }}{{ .Values.web.image.imageTag }}{{ else }}{{ .Values.global.image.imageTag }}{{ end }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            # - name: grpc
            #   containerPort: 50051
            #   protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: {{ .Values.web.livenessProbe.httpGet.path }}
          #     port: {{ .Values.web.livenessProbe.httpGet.port }}
          #   initialDelaySeconds: {{ .Values.web.livenessProbe.initialDelaySeconds }}
          #   timeoutSeconds: {{ .Values.web.livenessProbe.timeoutSeconds }}
          # readinessProbe:
          #   httpGet:
          #     path: {{ .Values.web.readinessProbe.httpGet.path }}
          #     port: {{ .Values.web.readinessProbe.httpGet.port }}
          #   initialDelaySeconds: {{ .Values.web.readinessProbe.initialDelaySeconds }}
          #   timeoutSeconds: {{ .Values.web.readinessProbe.timeoutSeconds }}
          # resources:
          #   limits:
          #     cpu: {{ .Values.web.resources.limits.cpu}}
          #     memory: {{ .Values.web.resources.limits.memory }}
          #   requests:
          #     cpu: {{ .Values.web.resources.requests.cpu }}
          #     memory: {{ .Values.web.resources.requests.memory }}
      {{- if .Values.web.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.web.nodeSelector "context" $) | nindent 8 }}
      {{ else if .Values.global.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.global.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

