name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ "main" ]  # Adjust this to match your default branch
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: NODE_OPTIONS="--max_old_space_size=4096" pnpm build
        env:
          NUXT_UI_PRO_LICENSE: "1234567890"
          NUXT_PUBLIC_SSAI_MANUAL_URL: "https://dev-streaming.gviet.vn:8783/api/sigma-demo-ssai/sessions/{sessionId}"
          NUXT_PUBLIC_PLAYER_URL: "https://dai.sigma.video/manifest/manipulation/master/e4a9ad52-a549-457d-8b1e-24fd842602b4/{sessionId}/manifest/dev-manual-ssai-demo/master.m3u8"
          NUXT_PUBLIC_SSAI_URL: "https://dai.sigma.video/manifest/manipulation/master/05feb022-8c58-4813-8214-c0b91393bc1a/manifest/channel-test/masterhls-ts-2s.m3u8"
          NUXT_PUBLIC_SSAI_ADS_ENDPOINT: "05feb022-8c58-4813-8214-c0b91393bc1a"
          NUXT_PUBLIC_SSAI_AI_RAW_URL: "https://cdn-lrm-test.sigma.video/manifest/channel-test/masterhls-ts-2s.m3u8"
          NUXT_PUBLIC_SSAI_AI_ADS_URL: "https://dai.sigma.video/manifest/manipulation/master/05feb022-8c58-4813-8214-c0b91393bc1a/manifest/channel-test/masterhls-ts-2s.m3u8"

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 168fa46ecfa0755b45fe5b273c753152
          command: pages deploy .output/public --project-name=sigma-web
