name: Docker Build and Push

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches: 
      - develop
      - main

env:
  HARBOR_REGISTRY: ${{ secrets.HARBOR_REGISTRY }}
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/sigma-streaming-platform-web

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Get Short SHA
        id: get_short_sha
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: brucewayne2610
          password: vukhanhnam123

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.SHORT_SHA }}
          load: true

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.SHORT_SHA }}
