name: Docker Build and Push

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches: 
      - develop
      - main

env:
  DOCKER_IMAGE: brucewayne2610/sigma-streaming-platform-web

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Get Short SHA
        id: get_short_sha
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: brucewayne2610
          password: vukhanhnam123

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.SHORT_SHA }}
          load: true

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.SHORT_SHA }}

      - name: Trigger pipeline in GitLab
        run: |
         curl -X POST \
          -F token=${{ secrets.TRIGGER_TOKEN }} \
          -F "ref=main" \
          -F "variables[IMAGE_TAG]=${{ env.SHORT_SHA }}" \
          https://${{ secrets.GITLAB_DNS }}/api/v4/projects/119/trigger/pipeline
