name: GitLabSync
run-name: ${{ github.actor }} Github sync to GitLab🚀
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync 
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: sigmaweb001/sigma-web@main
      with:
        target-url: repo.gviet.vn:1443/sigma-livestream/front-end/sigma-streaming-platform-website
        target-username: congnt
        target-token: 5g3cdiVe8a8k2t4NXq5G
